#! /bin/sh
#
# This is the postrm script for the Debian GNU/Linux units package
#
# Written by John G. Hasler    

set -e

#DEBHELPER#

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
 	if [ -x /usr/bin/update-menus ]
 	then
 	    update-menus
 	fi
        ;;
    *)
	echo "postrm called with unknown argument \`$1'" >&2
	;;
esac
